directories:
  output: dist-release
  buildResources: build
appId: com.cthulhu.cf-watching-you-always
productName: CF_Watching_you_always
files:
  - filter:
      - dist/**/*
      - dist-electron/**/*
mac:
  icon: public/icon.png
  target:
    - target: dmg
      arch:
        - x64
        - arm64
win:
  icon: public/icon.png
  target:
    - target: nsis
      arch:
        - x64
    - target: portable
      arch:
        - x64
linux:
  icon: public/icon.png
  target:
    - target: AppImage
      arch:
        - x64
nsis:
  oneClick: false
  allowToChangeInstallationDirectory: true
  createDesktopShortcut: true
  createStartMenuShortcut: true
  shortcutName: CF_Watching_you_always
electronVersion: 30.5.1
